/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const concepts = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  Concepts: [{ type: "autogenerated", dirName: "concepts" }],
};

const reference = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  "API Reference": [{ type: "autogenerated", dirName: "reference" }],
};

const integration = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  Integration: [{ type: "autogenerated", dirName: "integration" }],
};

module.exports = {
  concepts,
  reference,
  integration,
};
