name: "Trigger PR"

on:
  push:
    branches:
      - mk/test-trigger

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/env-setup
      - run: pnpm docs:graphql:generate
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Update Docs from updated GraphQL schema"

      - name: Trigger Rafiki Dev Update
        uses: actions/github-script@v5
        with:
          script: |
            const { data: existingPRs } = await github.rest.pulls.list({
              owner: 'interledger',
              repo: 'rafiki.dev',
              base: 'mk/test-trigger'
            });

            if (existingPRs.length === 0) {
              await github.rest.pulls.create({
                owner: 'interledger',
                repo: 'rafiki.dev',
                body: 'Testing',
                title: 'Publish New Docs',
                head: 'mk/test-trigger',
                base: 'main'
              });
            }
