name: "Trigger PR"

on:
  workflow_dispatch:

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Rafiki Dev Update
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.pulls.create({
              owner: 'interledger',
              repo: 'rafiki.dev',
              body: 'Testing',
              title: 'Publish New Docs',
              head: 'mk/test-trigger',
              base: 'main'
            });
