name: "Trigger PR"

on:
  push:
    branches: [mk/test-trigger]

jobs:
  open-pr:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
      - name: create pull request
        run: gh pr create -B main -H mk/test-trigger --title 'Merge mk/test-trigger into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
